# OPTRIXTRADES Bot Render Blueprint
# This file defines the services needed to deploy the OPTRIXTRADES bot to Render
# For detailed deployment instructions, see RENDER_DEPLOYMENT.md

services:
  - type: web
    name: optrixtrades-bot
    env: node
    buildCommand: npm install && node prepare-deploy.js
    startCommand: npm start
    plan: starter
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: IS_RENDER
        value: true
      - key: TELEGRAM_USE_WEBHOOK
        value: true
      - key: TELEGRAM_WEBHOOK_URL
        value: https://optrixtrades-bot.onrender.com/telegram-webhook
        # Note: Replace 'optrixtrades-bot' with your actual Render app name after deployment
      - key: TELEGRAM_WEBHOOK_SECRET
        sync: false
        # Secret token for webhook validation
      - key: TELEGRAM_BOT_TOKEN
        sync: false
        # Keep bot token as sync: false for security
      - key: ADMIN_TELEGRAM_IDS
        sync: false
      - key: PREMIUM_CHANNEL_ID
        sync: false
      - key: VIP_CHANNEL_ID
        sync: false
      - key: DB_HOST
        sync: false
        # Keep database credentials as sync: false for security
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
        # Never commit database passwords to version control
      - key: REDIS_HOST
        sync: false
        # For Render Redis, this should be the full Redis URL (redis://red-d1hroc3uibrs73fqp9k0:6379)
      # REDIS_PORT and REDIS_PASSWORD are not needed when using Redis URL
      # - key: REDIS_PORT
      #   sync: false
      # - key: REDIS_PASSWORD
      #   sync: false
      - key: USE_REDIS
        value: true
      - key: AWS_ACCESS_KEY_ID
        sync: false
        # Keep AWS credentials as sync: false for security
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
        # Keep AWS credentials as sync: false for security
      - key: AWS_REGION
        value: eu-north-1
      - key: AWS_S3_BUCKET
        value: optrixtrades
      - key: BROKER_API_URL
        value: https://iqoption.com/api
      - key: BROKER_WSS_URL
        value: wss://iqoption.com/echo/websocket
      - key: BROKER_AFFILIATE_LINK
        value: https://affiliate.iqbroker.com/redir/?aff=755757&aff_model=revenue&afftrack=